name: Deploy to Amazon

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  DeployDEV:
    name: Deploy on DEV
    runs-on: ubuntu-latest
    environment:
      name: Development
    defaults:
      run:
        working-directory: stages/newput-dev/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=region=${{ secrets.AWS_REGION }} -backend-config=access_key=${{ secrets.AWS_ACCESS_KEY_ID }} -backend-config=secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -var=region=${{ secrets.AWS_REGION }} -var=access_key=${{ secrets.AWS_ACCESS_KEY_ID }} -var=secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} -out tfplan

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve tfplan

  DestroyDEV:
    name: Destroy on DEV
    needs: [DeployDEV]
    runs-on: ubuntu-latest
    environment:
      name: Dev-Approver
    defaults:
      run:
        working-directory: stages/newput-dev/

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Terraform Init
        id: init
        run: terraform init -backend-config=region=${{ secrets.AWS_REGION }} -backend-config=access_key=${{ secrets.AWS_ACCESS_KEY_ID }} -backend-config=secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve -var=region=${{ secrets.AWS_REGION }} -var=access_key=${{ secrets.AWS_ACCESS_KEY_ID }} -var=secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
